### ISSUE TITLE
General Overview of Plugin - Boilerplate Setup

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-security-for-wordpress#1]
Pasted from Skype...

>[4/8/15, 12:33:08 AM] Andrew Angell: a PayPal Security Scanner for WordPress
>[4/8/15, 12:33:29 AM] Andrew Angell: so we'll scan all of the pages/posts on the WordPress site looking for standard PayPal buttons that are not hosted and are not encrypted.
>[4/8/15, 12:33:54 AM] Andrew Angell: And then we'll return a report showing them what it found and providing feedback on how they can improve their PayPal security.
>[4/8/15, 12:34:07 AM] Andrew Angell: Of course, this feedback will include things like using our PayPal Button Manager to create hosted buttons.

**Comment by angelleye** [comment]
We can use this first issue as our general setup issue.  Go ahead and get the plugin boilerplate all setup and ready to go with this new plugin.  

We're going to call the plugin "PayPal Security for WordPress".

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I am done with General Overview of Plugin-Setup and pushed to development branch.
