### ISSUE TITLE
Drop the "for-wordpress" from the end of the plugin name.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-security-for-wordpress#10]
We need to get rid of the "for-wordpress" at the end of the plugin name.  It should just be "paypal-security".  

Need to get that adjusted through-out the plugin.

**Comment by nishitlangaliya** [comment]
For this task I need to worked on lasted code, Once you review issue 12, 14, 15 and push to development then after I will start work with latest code.

**Comment by nishitlangaliya** [comment]
Done, Latest code pushed to development branch.
