### ISSUE TITLE
Add options for enabling/disabling post types.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-security-for-wordpress#12]
We need to add some check boxes for all of the post types available and allow people to check/uncheck post types to be included with the scanner.  

By default we can enable them all, but allow them to uncheck/disable if they need to for any post type.

This way if they know they don't have PayPal buttons on particular post types they can save a lot of time on the scan.

Of course, need to get that implemented into the scanner, too, so that it only runs through post types that are enabled.

**Comment by nishitlangaliya** [comment]
I have added options for enabling/disabling post types above scan now button and push to issue branch for your review.

**Comment by angelleye** [comment]
I have pulled the Development branch, uploaded all plugin files, and refreshed in the browser.  I am not seeing any options for the post types to scan above the scan now button..??

**Comment by angelleye** [comment]
We seem to be having some issues with the scanner when post types are selected, but we're handling that in #16
