### ISSUE TITLE
Add secure buttons to the scanner results.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-security-for-wordpress#14]
Right now the scanner is finding the secure buttons, but it's not including them in the display of results.

We need to go ahead and include the secure buttons in the results, but use a green check mark instead of the red x.

Also, separate them so it shows all the insecure buttons and then the secure buttons below that.

**Comment by nishitlangaliya** [comment]
I am done with this issue and push to issue #14 branch

**Comment by nishitlangaliya** [comment]
I am working on it once I am finalized it and test it will push  to development branch.

**Comment by angelleye** [comment]
I'm still not seeing the secure buttons that it finds included on the report..??

![image](https://cloud.githubusercontent.com/assets/629241/8350298/c9fced88-1ae9-11e5-9f3c-44ab88bebcf2.png)
