### ISSUE TITLE
View Cart button getting flagged as insecure.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-security-for-wordpress#15]
The View Cart button is getting flagged as insecure because is indeed a non-hosted button.  However, it does not contain any pricing detail, so we should not call it insecure.

What I would like to do, though, is if it finds a view cart button then check the value of the business parameter to see if it contains an @ symbol or not.  If so, then it's using an email address as a value here instead of the merchant account ID.

This scenario would be considered a "medium" risk because it does not contain item price info, but it does contain an email address which could be a privacy concern.  For this scenario we could use a yellow or orange warning icon and display it in the scan results as a medium risk.  

So the scan results would be High Risk buttons, Medium Risk Buttons, Secure buttons.

For now, only a View Cart button with the email address used would be flagged as medium, but we may have more in the future.

**Comment by nishitlangaliya** [comment]
I am done with this issue and push to issue #14 branch

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I have merged code of Issue -12,14,15 Into 'Issue-12-14-15' branch as it was dependent on each other  .  so please review  'Issue-12-14-15' and let me know your thoughts and suggestions. Once you confirm I will push it to development branch.

**Comment by angelleye** [comment]
Remember, I said you could go ahead and merge everything in this one into the dev branch since it hasn't been officially launched yet.  

So please go ahead and do that and I'll just review the dev branch.

**Comment by nishitlangaliya** [comment]
Latest code pushed to development branch

**Comment by angelleye** [comment]
I see these showing up as medium risk buttons, which is good, but the Remarks column says "Shopping Cart Button".  It should say "View Cart Button" instead.

Also, the buttons it's finding aren't actually a medium risk.  As I explained above, the only time a View Cart button would be a medium risk is if the business parameter was set with an email address as the value.  

The buttons being returned right now each have a merchant account ID as the value for the business parameter instead of an email address, so they would be considered secure.
