### ISSUE TITLE
Report Design Adjustment

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-security-for-wordpress#17]
I'd like to make some adjustments to the overall layout here.

![image](https://cloud.githubusercontent.com/assets/629241/8371389/87d8d882-1b9c-11e5-8541-13f2ec90fed8.png)

**Comment by angelleye** [comment]
Also, please center the Page ID column values.

**Comment by angelleye** [comment]
I don't think we need a column for Page ID here.  Instead, that column could be where we put the icon showing whether the button's security status (#18).

Then, I think we could have just 1 other column called Button Details, and within that we would have bullet points based on the type of button.

For secure buttons, we would have...

* Page URL: http://domain.com/button-page/
* Button Security Status: High
* Pricing Concern: None
* Privacy Concern: None

For insecure, medium buttons (which again, for now are only View Cart buttons that have an email address displayed in the business parameter) we would have...

* Page URL: http://domain.com/button-page/
* Button Security Status: Medium
* Pricing Concern:  None
* Privacy Concern: Email address displayed in the button code.

And then for insecure, high risk buttons, we would have...

* Page URL: http://domain.com/button-page/
* Button Security Status: Low
* Pricing Concern: Vulnerable to pricing adjustments prior to submitting payment.
* Privacy Concern: Email address displayed in the button code.

**Comment by angelleye** [comment]
Also, I think we can just have a single table sorted by the risk instead of separate tables for each risk type.

**Comment by angelleye** [comment]
Here is a graphical look at what I'd like to accomplish with the report design.

![image](https://cloud.githubusercontent.com/assets/629241/8374490/6d8bdb4a-1bbb-11e5-8ecf-7f515c093b36.png)

**Comment by angelleye** [comment]
I would also like to adjust this section...

![image](https://cloud.githubusercontent.com/assets/629241/8374619/6ac4ae0e-1bbc-11e5-9479-738d49c55e64.png)

The top portion has a bunch of open space to the right of the check boxes and the scan button.  I'd like to move the box that outlines the number of pages scanned and buttons found up into that section so we aren't wasting so much space.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I am in middle of the functionality. as we discussed and the visual suggested by you. once I will finalized it. will push to latest code for a review.

**Comment by angelleye** [comment]
This is a rough draft of what I'm thinking overall...

![image](https://cloud.githubusercontent.com/assets/629241/8401640/1461fb92-1df7-11e5-89fa-c527db28703d.png)

**Comment by nishitlangaliya** [comment]
Hi Andrew

I am done with updated desing view. and pushed latest code to "Development" branch for a review. please check for the same and let me know your thoughts for the same.

**Comment by angelleye** [comment]
Let's try making the icons about half the size as they are now.

Also, can we add pagination within this in case people have a bunch of buttons?  Standard pagination with the ability to choose how many to display per page..??

**Comment by angelleye** [comment]
Also, let's go with valign=center on th bullet points in the row instead of top.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

 I am done with size of a icon and vertical align= middle.
 Regarding Pagination please see my comment below:
 I played with jquery datatable but didnt worked so we can have two options for pagination:
 
 1 ) We can add just simple javascript pagination by hide show number of rows.
 2) For standard wordpress table pagination we have to be have table saved in database.

 Please let me know your thoughts and suggestions for the same.

**Comment by angelleye** [comment]
I'm not sure I understand how #1 would work..??

**Comment by angelleye** [comment]
We can think about adding pagination later.  Closing this issue.
