### ISSUE TITLE
Percentage Display in Results / Report

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-security-for-wordpress#20]
When the report is complete we can calculate the percentage of buttons that are not secure and display that in the table at the top.  So if they have 100 buttons and 78 of them are insecure, we would display that 78% of their buttons are insecure.

With that we can provide a [letter grade](http://www.cs.uni.edu/~mccormic/lettergrade.html), and display that as a big letter in that top, header portion next to the results table.

**Comment by angelleye** [comment]
Something like this...

![image](https://cloud.githubusercontent.com/assets/629241/8408282/454b8880-1e34-11e5-8800-42791c58a6e1.png)

The color for the grade letter would be different based on the score...

A = Dark Green

A-, B+, B = Light Green

C+, C, C- = Light Yellow

D+, D, D- = Dark Yellow

F = RED

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I have started working on logic we discussed. Once I am done will let you know for the same.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

Hi  I am done with the issue. and pushed latest code into Development branch for a review.

**Comment by angelleye** [comment]
The criteria for letter grade isn't working as expected.  I just ran a scan of 70% but it gave me a grade of an F.  70% should be a C-.

**Comment by nishitlangaliya** [comment]
Yes I see , will handle with Issue - #19.

**Comment by nishitlangaliya** [comment]
Hi Andrew

As per our discussion I applied changes to scan now portion. and pushed latest code to Development branch please check for the same and let me know your thoughts.


![screenshot-bmw dev2 in 2015-07-02 11-40-14](https://cloud.githubusercontent.com/assets/11435772/8470929/07698e3a-20b0-11e5-9fed-096ca931a244.png)

**Comment by angelleye** [comment]
Can we make the bottom of the Site Score box line up with the bottom of the note/count table?  I want the height of both of those to be the same.

**Comment by nishitlangaliya** [comment]
Done, Latest code pushed to development branch.

![screenshot-bmw dev2 in 2015-07-02 18-43-38](https://cloud.githubusercontent.com/assets/11435772/8477856/045e21e8-20eb-11e5-803d-d817b68bbd61.png)

**Comment by angelleye** [comment]
The Note/Count table seems to resize itself based on resizing the browser window (responsive) but the Site Score box is not doing that.  As such, they're getting out of line depending on the size of the window.

See this video for a review of what I'm talking about:  http://fiber.angelleye.com/forums/github/paypal-security-20.mp4

**Comment by nishitlangaliya** [comment]
Hi Andrew,

Done , SIte score button box is now resizable. latest code pushed to "Development" branch for a review.
