### ISSUE TITLE
Recommendation

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-security-for-wordpress#21]
The last thing we need to do here is provide a recommendation for how to secure any buttons that come back as insecure.

Of course, our recommendation is going to be that they use the PayPal WP Button Manager plugin to create new buttons to replace the insecure buttons with.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

Would you please provide me one rough sketch for in which part you want to display recommendation and what would be text and links etc. that would be great.

**Comment by angelleye** [comment]
All I'm looking for here is a div / box that gets displayed if their site has any un-secure buttons where we can display some basic info about our PayPal WP Button Manager plugin and a link/button to install it.  

Many other plugins do similar things, so we can follow the design of some other plugin if we need to.  

Again, though, just something simple that shows up on the report after the scan is done letting them know how to solve their problem...which is to install the Button Manager plugin and replace their un-secure buttons when secure buttons generated by that plugin.

**Comment by kcppdevelopers** [comment]
For more information view the screenshot <a href="http://www.awesomescreenshot.com/image/623981/ef10cc55907df2fd7b823d0c1c664b2f"> here</a>

**Comment by angelleye** [comment]
The screenshot looks good.  Can we add a button/link to automatically install the plugin from within the box, too?

**Comment by angelleye** [comment]
I have pulled all the latest changes here, but when I run a scan I do not see the recommendation.  This is what I get.

![image](https://cloud.githubusercontent.com/assets/629241/10363824/70b48e8a-6d7c-11e5-8737-01bd3c5bf6ae.png)
