### ISSUE TITLE
Scanner Problem

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-security-for-wordpress#22]
You mentioned that you made some improvements to the scanning process, however, it seems that something that was done has broken it.

On woo.angelleye.com I have [this page](http://woo.angelleye.com/sample-page/?v=fef5f5d4a1dd) that has quite a few buttons on it.  The scanner is not picking them up.

When I run the scanner it completes very quickly (seems too fast, almost instant) and returns that it found 0 buttons.

**Comment by kcppdevelopers** [comment]
I have setup this plugin <a href="http://kcppdevelopers.angelleye.com/wp-admin/tools.php?page=paypal-security"> here</a>

**Comment by angelleye** [comment]
I'm confused.  I don't see any commits here to resolve the issue I mentioned..??

**Comment by kcppdevelopers** [comment]
Actually, when you test plugin that time issue #7 is in progress, that why is scanning process is broken. Now it's working fine.

**Comment by angelleye** [comment]
Ah, ok, I will try again.  Thanks.

**Comment by angelleye** [comment]
This is still not working correctly for me.  [Here is a video](http://fiber.angelleye.com/temp/paypal-security-22.mp4)
.
