### ISSUE TITLE
Scan Report

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-security-for-wordpress#3]
Need to create a nice looking report that outlines everything the scanner finds as well as details about what actions the user should take to fix their problems.

We could base this off other security scanner tools for WordPress if we need to.  Just need to come up with a nice looking interface that's easy to understand and displays all of the buttons that the scanner found which are insecure with a note about why it's insecure and how it could be fixed.

I'll try to come up with a template of how I'd like this report to look, but if you get here before I get that done and you have questions just let me know.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I have uploaded latest code to development branch please review it and let me know your thoughts and suggestions for the same. I have attached the what I am done with the report and functionality.

![issue-2](https://cloud.githubusercontent.com/assets/11435772/7254096/7887297c-e85e-11e4-9fac-cfb6536bdd14.png)

**Comment by angelleye** [comment]
I don't like all of the code that shows up on this report the way it is now.  It doesn't look pretty and will scare people away from wanting to look at it.

I do like the idea of showing that, but may be we can display a simple list of the buttons it finds on each page, and then when you hover over the list item it would pop-up a lightbox window that shows you the actual code.

We could even parse out the cmd and item_name values for the list.  For example, instead of of the 3 boxes of code we're getting now for your page ID 1442, we might see...

* Cart Button - Shirt
* Cart Button - Shoes
* Cart Button - Hat

So we would know it was a "Cart Button" based on the cmd="_cart" value and then we simply display the item_name next to that to make a nice list for each page.  Probably should make it multiple columns / divs, too, and only show maybe 5 - 10 buttons per div so that it lists everything across all of the space instead of 1 really long list.

That will leave us more room to provide better information about what it's finding and make it look a little more pretty, and then I'll jump in and help with what I want it to actually say.

**Comment by angelleye** [comment]
Maybe what we could do, too, is add little green check marks next to the buttons that are secure and red x's next to the buttons that are insecure.  Seems like that's a typical thing I would see on security scans similar to this.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I am in middle of this functionality Once I am done will push it development branch and let you know for the same.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I have done some functionality to display the reports . and also done the changes as we discuss in skepe for display unsecured button like below.

Buy Now Button - Hat

Subscription Button - Newsletter

Donation Button - Red Cross

I am attaching the screenshot of a current senario. and pushed the latest code to development branch for review, so please let me know your thoughts and suggestions for the same.

Note : currently search report and view source functionality is not done . I have put just html of it.

![issue-3b](https://cloud.githubusercontent.com/assets/11435772/7321199/8100b2e6-eabe-11e4-9446-4a3964f7ba88.png)

**Comment by angelleye** [comment]
I like the table portion of this, although, the Page ID column doesn't need to be as wide as it is.  Could have more room for the URL column.  Some URL's will be rather long I'm sure.  Otherwise, I think the idea behind the table looks good.  Just a general list of the pages that were found with a PayPal button on them, and then show details about the type of button it found and whether or not it's secure.

The small table of results doesn't need to be so colorful.  Let's make that a little bit more subtle like the primary table below it.

**Comment by angelleye** [comment]
For now, we can hold off on saving the reports and providing a history/search.  We'll add that in a new issue later.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I am done with changes according to above comments. and pushed latest code to development branch. please review it and let me know your thoughts for the same.
