### ISSUE TITLE
PayPal IPN for WordPress Installer

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-security-for-wordpress#39]
When you run the scanner and get the recommendation, if you don't have PayPal IPN for WordPress installed it gives you a button to install it.

When it installs, though, it's installing to /plugins/paypal-ipn-for-wordpress

The WordPress directory uses just /plugins/paypal-ipn

We need to update this to match that and use use /paypal-ipn as the plugin directory name when it installs through that button.

**Comment by kcppdevelopers** [comment]
I am little bit confused here, Actually we are displaying recommendation for PayPal WP Button Manager plugin not PayPal IPN for WordPress plugin. so you mean we should recommend both plugin?

**Comment by angelleye** [comment]
Hmmm...I am confused now, too, looking back at this.  I will have to play with this again and figure out what I was running into here.

**Comment by deepakmaurya** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**Worker have applied to start work.**

Below user(s) claimed they can complete the work within defined time period.

Please review their action plans below:

**1) <a href='https://sandbox.gitworkdone.com/profile/drewbuyer'>drewbuyer</a> has applied to start work. (Funders only: <a href='https://sandbox.gitworkdone.com/issue/build-an-installer-for-the-plugin?action=approve&worker=drewbuyer'>approve worker</a> | <a href='https://sandbox.gitworkdone.com/issue/build-an-installer-for-the-plugin?action=reject&worker=drewbuyer'>reject worker</a>)**
                
**Message:** I would like to complete this task.




<a href='https://sandbox.gitworkdone.com/issue/build-an-installer-for-the-plugin'>Click Here to view more</a> on GitWorkDone Bounty detail page.

**Comment by deepakmaurya** [comment]
Issue Status: 1. Open 2. **Started**  3. Submitted 4. Done

<hr>

**Work has been started.**

**<a href='https://sandbox.gitworkdone.com/profile/drewbuyer'>drewbuyer</a> has been approved to start work.**

<hr />

**Message:** Sure, go ahead and get started please!


<a href='https://sandbox.gitworkdone.com/issue/build-an-installer-for-the-plugin'>Click Here to view more</a> on GitWorkDone Bounty detail page.

**Comment by deepakmaurya** [comment]
**<a href='https://sandbox.gitworkdone.com/profile/angelleye'>https://sandbox.gitworkdone.com/profile/drewbuyer</a> Work has been approved by <a href='drewbuyer'>angelleye</a>.**
<hr />

**Message:** thank you for the good work!


<a href='https://sandbox.gitworkdone.com/issue/build-an-installer-for-the-plugin'>Click Here to view more</a> on GitWorkDone Bounty detail page.

**Comment by angelleye** [comment]
Above comments from GitWorkDone are from testing in the sandbox.  Ignore.
