### ISSUE TITLE
PayPal Standard Button Filter

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-security-for-wordpress#5]
We're doing the same thing here that Jignesh did in the IPN plugin, where we check every page as it loads to search for a PayPal standard button, and if it finds it, we inject our BN code into it.

https://bitbucket.org/angelleye/paypal-ipn-for-wordpress/commits/798fbc07076a

**Comment by nishitlangaliya** [comment]
Hi Andrew,

Started to work on this issue , I am in middle of this functionality. once I am finalized will let you know for the same.

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I am done with this issue. latest code uploaded to development branch. please check for the same.

**Comment by nishitlangaliya** [comment]
Hi Andrew, 

php error notice removed.

**Comment by angelleye** [comment]
We actually made an adjustment to this jQuery logic so that it will catch more buttons more accurately.  Take a look at the very bottom of this page:  https://bitbucket.org/angelleye/paypal-ipn-for-wordpress/commits/c0ec0bcd9f64

Please make the same adjustment here.
