### ISSUE TITLE
Move the tool to Tools instead of Settings.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-security-for-wordpress#6]
Right now we have the tool under Settings -> PayPal Security for WordPress.  This doesn't really make sense because all we have right now is the tool itself.  We don't even have any settings at this point.

I'd like to move the link for the tool to Tools -> PayPal Security (we can drop "for WordPress"), and then later if we add settings to this thing that would then go under Settings -> PayPal Security.

**Comment by nishitlangaliya** [comment]
Done, Latest code pushed to development branch.
